spring:
  application:
    name: app
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${IV_DATASOURCE_URL}
    username: ${IV_DATASOURCE_USERNAME}
    password: ${IV_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: localhost
    port: 1025
    properties:
        "[mail.smtp.auth]": false
        "[mail.smtp.starttls.enable]": false

app:
  url: http://localhost:8080/
  from-email: george@inboxview.com

jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  access-token-ttl: 15m
  refresh-token-ttl: 1440m