spring:
  application:
    name: app
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/inboxview_app_db1
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver

jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  ttl: 15m