name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Allow mvn execute permission
      run: chmod +x mvnw
        
    - name: Create private key from secret
      run: | 
        echo "${{ secrets.INBOXVIEW_APP_PRIVATE_KEY }}" | base64 -d > src/main/resources/jwt/app.key
    - name: Build with Maven
      run: ./mvnw package

    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@v1.1.2
      with:
        name: nabuage/inboxview-app
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Deploy to render using webhook
      run: curl ${{ secrets.RENDER_WEBHOOK }}